name: vamsl
channels:
- conda-forge
dependencies:
- numpy
- python=3.11
- imageio
- tqdm
- matplotlib
- igraph
- scikit-learn
- jupyter
- pip
- pip:
    - "jax[cuda12]==0.4.26 -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html"
    - flax
    - dm-haiku
    - dm-sonnet
    - reverb
    - .
